title: Hey there
author: Tianyi Zz
email: tianyi.zhu@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  An awesome description

# social links
twitter_username: not for public
github_username:  take a guess

show_excerpts: true # set to false to remove excerpts on the homepage

theme: to minima
